### ISSUE TITLE
Value of <br tag of type Java.lang.string cannot be converted 

### ISSUE THREAD

**Issue by Skut26** [AbrarJahin/Android_Login-And-Register-User#3]
I get this error.. Stumbled for 5 days help me

**Comment by DalalAlmutawa** [comment]
I am also please help me

**Comment by DalalAlmutawa** [comment]
Value <br of type java.lang.String cannot be converted to JSONObject
 at com.appnucleus.loginandregisteruser.Activity_Login$3.onResponse(Activity_Login.java:110)

**Comment by AbrarJahin** [comment]
Sorry for being late.

I am checking this error and it will be solved ASAP.

Thanks @Skut26 for finding the error

**Comment by majidparan** [comment]
Error : 
Value <br of type java.lang.String cannot be converted to JSONObject
at com.appnucleus.loginandregisteruser.Activity_Login$3.onResponse(Activity_Login.java:110)
Reason : 
$user = $stmt->get_result()->fetch_assoc();
